version: '3.3'

services:
  swagger-ui:
    image: mrin9/rapidoc
    environment:
      SPEC_URL: http://localhost:5000/v1/openapi
      RAPIDOC_OPTIONS: "theme='dark' allow-authentication='true' "
    ports:
      - 8112:80
  nginx:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    environment:
      NGINX_PORT: 5000
      NGINX_HOST: 127.0.0.1
    network_mode: host
    expose:
      - 5000